package com.epam.kinorating.config;

public class Attribute {
    public static final String ATTRIBUTE_SEARCH = "search";
    public static final String ATTRIBUTE_MOVIES = "movies";
    public static final String ATTRIBUTE_ERROR_MESSAGE = "errmessage";
    public static final String ATTRIBUTE_USERNAME = "username";
    public static final String ATTRIBUTE_PASSWORD = "pwd";
    public static final String ATTRIBUTE_MAIL = "mail";
    public static final String ATTRIBUTE_USER = "user";
    public static final String ATTRIBUTE_ERROR_ENTER = "errorEnter";
    public static final String ATTRIBUTE_ACCESS_ERROR = "accessError";
    public static final String ATTRIBUTE_MOVIE_ID = "movieId";
    public static final String ATTRIBUTE_REVIEW = "review";
    public static final String ATTRIBUTE_MOVIE_RATING = "rating";
    public static final String ATTRIBUTE_RATINGS_NUMBER = "numberOfRatings";
    public static final String ATTRIBUTE_MOVIE = "movie";
    public static final String ATTRIBUTE_USER_ACTION_LIST = "userActionList";
    public static final String ATTRIBUTE_IS_RATED = "isRated";
    public static final String ATTRIBUTE_PAGE = "page";
    public static final String ATTRIBUTE_VALUATION = "valuation";
    public static final String ATTRIBUTE_NAME_RU = "name_ru";
    public static final String ATTRIBUTE_NAME_EN = "name_en";
    public static final String ATTRIBUTE_GENRE_RU = "genre_ru";
    public static final String ATTRIBUTE_GENRE_EN = "genre_en";
    public static final String ATTRIBUTE_TITLE_EN = "title_en";
    public static final String ATTRIBUTE_TITLE_RU = "title_ru";
    public static final String ATTRIBUTE_COUNTRY_RU = "country_ru";
    public static final String ATTRIBUTE_COUNTRY_EN = "country_en";
    public static final String ATTRIBUTE_CAST_EN = "cast_en";
    public static final String ATTRIBUTE_CAST_RU = "cast_ru";
    public static final String ATTRIBUTE_AWARDS_RU = "awards_ru";
    public static final String ATTRIBUTE_AWARDS_EN = "awards_en";
    public static final String ATTRIBUTE_TVSERIAL = "tvSerial";
    public static final String ATTRIBUTE_YEAR = "year";
    public static final String ATTRIBUTE_DURATION = "duration";
    public static final String ATTRIBUTE_USER_ID = "id";
    public static final String ATTRIBUTE_USER_RATING = "rating";
    public static final String ATTRIBUTE_USER_LIST = "users";
    public static final String ATTRIBUTE_IMAGE = "image";
}
